import { Router } from 'express';
import authRoutes from './auth.routes';
import countriesRoutes from './countries.routes';
import campaignsRoutes from './campaigns.routes';
import creativesRoutes from './creatives.routes';
import contentRoutes from './content.routes';
import productsRoutes from './products.routes';
import productFeaturesRoutes from './product-features.routes';
import budgetRoutes from './budget.routes';
import alertsRoutes from './alerts.routes';
import settingsRoutes from './settings.routes';
import agentsRoutes from './agents.routes';
import killswitchRoutes from './killswitch.routes';
import infrastructureRoutes from './infrastructure.routes';
import auditRoutes from './audit.routes';
import dashboardRoutes from './dashboard.routes';
import webhooksRoutes from './webhooks.routes';
import queueRoutes from './queue.routes';
import ratelimitRoutes from './ratelimit.routes';
import notificationsRoutes from './notifications.routes';
import apikeysRoutes from './apikeys.routes';
import finalOutputsRoutes from './final-outputs.routes';
import finalOutputsStrategyRoutes from './final-outputs-strategy.routes';
import finalOutputsConfidenceRoutes from './final-outputs-confidence.routes';
import finalOutputsBudgetRoutes from './final-outputs-budget.routes';
import finalOutputsWeaknessRoutes from './final-outputs-weakness.routes';
import finalOutputsRoadmapRoutes from './final-outputs-roadmap.routes';
import finalOutputsValidationRoutes from './final-outputs-validation.routes';
import mfaRoutes from './mfa.routes';
import metricsRoutes from './metrics.routes';
import featureFlagsRoutes from './feature-flags.routes';
import workflowRoutes from './workflow.routes';
import learningRoutes from './learning.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/countries', countriesRoutes);
router.use('/campaigns', campaignsRoutes);
router.use('/creatives', creativesRoutes);
router.use('/content', contentRoutes);
router.use('/products', productsRoutes);
router.use('/products', productFeaturesRoutes);
router.use('/budget', budgetRoutes);
router.use('/alerts', alertsRoutes);
router.use('/settings', settingsRoutes);
router.use('/agents', agentsRoutes);
router.use('/killswitch', killswitchRoutes);
router.use('/infrastructure', infrastructureRoutes);
router.use('/audit', auditRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/webhooks', webhooksRoutes);
router.use('/queue', queueRoutes);
router.use('/ratelimits', ratelimitRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/apikeys', apikeysRoutes);
router.use('/final-outputs', finalOutputsRoutes);
router.use('/final-outputs', finalOutputsStrategyRoutes);
router.use('/final-outputs', finalOutputsConfidenceRoutes);
router.use('/final-outputs/budget-model', finalOutputsBudgetRoutes);
router.use('/final-outputs/weakness-report', finalOutputsWeaknessRoutes);
router.use('/final-outputs', finalOutputsRoadmapRoutes);
router.use('/final-outputs', finalOutputsValidationRoutes);
router.use('/mfa', mfaRoutes);
router.use('/feature-flags', featureFlagsRoutes);
router.use('/workflows', workflowRoutes);
router.use('/learning', learningRoutes);

// Metrics
router.use('/metrics', metricsRoutes);

export default router;
