// ============================================================
// AI Integration Layer - Type Definitions
// Phase 3B: Anthropic API Integration
// ============================================================

/**
 * Supported Anthropic model tiers.
 */
export type AIModelType = 'opus' | 'sonnet';

/**
 * Represents a request to an Anthropic AI model.
 */
export interface AIRequest {
  /** Which model tier to use for this request. */
  model: AIModelType;
  /** The system-level prompt that sets context/behavior for the model. */
  systemPrompt: string;
  /** The user-level prompt containing the actual task or question. */
  userPrompt: string;
  /** Maximum number of tokens to generate in the response. */
  maxTokens?: number;
  /** Sampling temperature (0.0 = deterministic, 1.0 = creative). */
  temperature?: number;
  /** Arbitrary metadata attached to the request for tracking/logging. */
  metadata?: Record<string, unknown>;
}

/**
 * Token usage breakdown for a single AI request.
 */
export interface TokenUsage {
  /** Number of tokens in the input (system + user prompts). */
  inputTokens: number;
  /** Number of tokens generated in the response. */
  outputTokens: number;
  /** Total tokens consumed (input + output). */
  totalTokens: number;
}

/**
 * Represents a response from an Anthropic AI model.
 */
export interface AIResponse {
  /** The text content generated by the model. */
  content: string;
  /** The specific model identifier used (e.g. claude-opus-4-20250514). */
  model: string;
  /** Token usage breakdown for this request. */
  usage: TokenUsage;
  /** Unique identifier for this request/response pair. */
  requestId: string;
  /** Wall-clock latency in milliseconds for the API call. */
  latencyMs: number;
}

/**
 * A record tracking cost for a single AI API call, persisted to the database.
 */
export interface CostRecord {
  /** Unique identifier for this cost record. */
  id: string;
  /** The agent type that made the request. */
  agentType: string;
  /** The model identifier used. */
  model: string;
  /** Number of input tokens consumed. */
  inputTokens: number;
  /** Number of output tokens generated. */
  outputTokens: number;
  /** Computed cost in USD for this request. */
  cost: number;
  /** The request ID this cost is associated with. */
  requestId: string;
  /** ISO 8601 timestamp of when this cost was recorded. */
  timestamp: string;
}

/**
 * Summarized cost data for reporting.
 */
export interface CostSummary {
  /** Total cost in USD. */
  totalCost: number;
  /** Total number of requests made. */
  totalRequests: number;
  /** Total input tokens consumed. */
  totalInputTokens: number;
  /** Total output tokens generated. */
  totalOutputTokens: number;
  /** Breakdown by model. */
  byModel: Record<string, {
    cost: number;
    requests: number;
    inputTokens: number;
    outputTokens: number;
  }>;
}

/**
 * Configuration for the rate limiter.
 */
export interface RateLimitConfig {
  /** Maximum number of API requests allowed per minute. */
  maxRequestsPerMinute: number;
  /** Maximum number of tokens allowed per minute. */
  maxTokensPerMinute: number;
  /** Maximum number of concurrent in-flight requests. */
  maxConcurrent: number;
}

/**
 * Status snapshot of the rate limiter.
 */
export interface RateLimitStatus {
  /** Number of available concurrency slots. */
  availableSlots: number;
  /** Number of requests waiting in the queue. */
  queueLength: number;
}

/**
 * Per-model pricing configuration (cost per million tokens in USD).
 */
export interface ModelPricing {
  /** Cost per million input tokens in USD. */
  inputPerMTok: number;
  /** Cost per million output tokens in USD. */
  outputPerMTok: number;
}

/**
 * Result of validating an AI response.
 */
export interface ValidationResult {
  /** Whether the response passed all validation checks. */
  valid: boolean;
  /** List of validation error messages (empty if valid). */
  errors: string[];
}

/**
 * Result of validating/parsing JSON content.
 */
export interface JSONValidationResult {
  /** Whether the content is valid JSON. */
  valid: boolean;
  /** The parsed JSON value (present only if valid). */
  parsed?: unknown;
  /** Parse error message (present only if invalid). */
  error?: string;
}
